name: Deploy to Azure VM

on: 
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            - name: SSH into VM & Deploy
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VM_HOST }}
                username: ${{ secrets.VM_USERNAME }}
                key: ${{ secrets.VM_SSH_KEY }}
                script: |
                  cd ~/docker-nginx-azure
                  pwd
                  git pull origin main
                  sudo docker-compose down
                  sudo docker-compose up -d --build